version : "3.9"

services:
  node:
    container_name: util
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"